[context.production.environment]
NEXT_PUBLIC_SANITY_DATASET = "production"
NEXT_PUBLIC_API_URI = "https://api.regen.network"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LeqBFIaAAAAAPfLave4lUtLBKF2WYXinbaLNFqB"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-N7DHYF5D4J"
NEXT_PUBLIC_SANITY_PROJECT_ID = "jm12rn9t"
NEXT_PUBLIC_SANITY_TAG = "default"

[context.dev.environment]
NEXT_PUBLIC_SANITY_DATASET = "staging"
NEXT_PUBLIC_API_URI = "https://api-staging.regen.network"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-20LDV9DJHX"
NEXT_PUBLIC_SANITY_PROJECT_ID = "jm12rn9t"
NEXT_PUBLIC_SANITY_TAG = "default"

[context.deploy-preview.environment]
NEXT_PUBLIC_SANITY_DATASET = "staging"
NEXT_PUBLIC_API_URI = "https://api-staging.regen.network"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-20LDV9DJHX"
NEXT_PUBLIC_SANITY_PROJECT_ID = "jm12rn9t"
NEXT_PUBLIC_SANITY_TAG = "default"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=10216"

[[plugins]]
package = "@netlify/plugin-nextjs"